// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.0
//   protoc               v7.35.1
// source: ai-query.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from '@bufbuild/protobuf/wire'
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from '@grpc/grpc-js'

export const protobufPackage = 'cortex.search'

/**
 * Why an enum and not a `bool degraded`: search-service returns `summary: null`
 * for TWO very different reasons — the AI provider is down/circuit-open, and
 * "the org's knowledge base had nothing to answer from". Billing must treat them
 * differently (neither is charged, but only the first is a 503 the user should
 * retry), and a bool collapses them into one indistinguishable case.
 */
export enum RagOutcome {
  RAG_OUTCOME_UNSPECIFIED = 0,
  /** RAG_OUTCOME_ANSWERED - Retrieval found chunks AND the summarizer produced an answer — chargeable. */
  RAG_OUTCOME_ANSWERED = 1,
  /**
   * RAG_OUTCOME_NO_RESULTS - Retrieval legitimately found nothing. Not a failure, not chargeable: HTTP 200
   * with a null answer, no compensation needed beyond releasing the hold.
   */
  RAG_OUTCOME_NO_RESULTS = 2,
  /**
   * RAG_OUTCOME_AI_UNAVAILABLE - Chunks were retrieved but the summarizer failed / its breaker is open. The
   * user did not get what they would have paid for → 503 + release the hold.
   */
  RAG_OUTCOME_AI_UNAVAILABLE = 3,
  UNRECOGNIZED = -1,
}

export function ragOutcomeFromJSON(object: any): RagOutcome {
  switch (object) {
    case 0:
    case 'RAG_OUTCOME_UNSPECIFIED':
      return RagOutcome.RAG_OUTCOME_UNSPECIFIED
    case 1:
    case 'RAG_OUTCOME_ANSWERED':
      return RagOutcome.RAG_OUTCOME_ANSWERED
    case 2:
    case 'RAG_OUTCOME_NO_RESULTS':
      return RagOutcome.RAG_OUTCOME_NO_RESULTS
    case 3:
    case 'RAG_OUTCOME_AI_UNAVAILABLE':
      return RagOutcome.RAG_OUTCOME_AI_UNAVAILABLE
    case -1:
    case 'UNRECOGNIZED':
    default:
      return RagOutcome.UNRECOGNIZED
  }
}

export function ragOutcomeToJSON(object: RagOutcome): string {
  switch (object) {
    case RagOutcome.RAG_OUTCOME_UNSPECIFIED:
      return 'RAG_OUTCOME_UNSPECIFIED'
    case RagOutcome.RAG_OUTCOME_ANSWERED:
      return 'RAG_OUTCOME_ANSWERED'
    case RagOutcome.RAG_OUTCOME_NO_RESULTS:
      return 'RAG_OUTCOME_NO_RESULTS'
    case RagOutcome.RAG_OUTCOME_AI_UNAVAILABLE:
      return 'RAG_OUTCOME_AI_UNAVAILABLE'
    case RagOutcome.UNRECOGNIZED:
    default:
      return 'UNRECOGNIZED'
  }
}

export interface RagQueryRequest {
  orgId: string
  question: string
  topK: number
}

export interface RagQueryResponse {
  outcome: RagOutcome
  /** Empty unless outcome == ANSWERED. */
  summary: string
  sources: RagSource[]
  /**
   * Retrieved chunks, always populated when retrieval found anything — returned
   * even on AI_UNAVAILABLE so the caller can serve them as a fallback (UC-C2).
   */
  chunks: RagChunk[]
}

export interface RagSource {
  knowledgeItemId: string
  title: string
}

export interface RagChunk {
  knowledgeItemId: string
  titleSnapshot: string
  content: string
  score: number
}

function createBaseRagQueryRequest(): RagQueryRequest {
  return { orgId: '', question: '', topK: 0 }
}

export const RagQueryRequest: MessageFns<RagQueryRequest> = {
  encode(message: RagQueryRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.orgId !== '') {
      writer.uint32(10).string(message.orgId)
    }
    if (message.question !== '') {
      writer.uint32(18).string(message.question)
    }
    if (message.topK !== 0) {
      writer.uint32(24).int32(message.topK)
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RagQueryRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseRagQueryRequest()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.orgId = reader.string()
          continue
        }
        case 2: {
          if (tag !== 18) {
            break
          }

          message.question = reader.string()
          continue
        }
        case 3: {
          if (tag !== 24) {
            break
          }

          message.topK = reader.int32()
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): RagQueryRequest {
    return {
      orgId: isSet(object.orgId)
        ? globalThis.String(object.orgId)
        : isSet(object.org_id)
          ? globalThis.String(object.org_id)
          : '',
      question: isSet(object.question) ? globalThis.String(object.question) : '',
      topK: isSet(object.topK)
        ? globalThis.Number(object.topK)
        : isSet(object.top_k)
          ? globalThis.Number(object.top_k)
          : 0,
    }
  },

  toJSON(message: RagQueryRequest): unknown {
    const obj: any = {}
    if (message.orgId !== '') {
      obj.orgId = message.orgId
    }
    if (message.question !== '') {
      obj.question = message.question
    }
    if (message.topK !== 0) {
      obj.topK = Math.round(message.topK)
    }
    return obj
  },

  create<I extends Exact<DeepPartial<RagQueryRequest>, I>>(base?: I): RagQueryRequest {
    return RagQueryRequest.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<RagQueryRequest>, I>>(object: I): RagQueryRequest {
    const message = createBaseRagQueryRequest()
    message.orgId = object.orgId ?? ''
    message.question = object.question ?? ''
    message.topK = object.topK ?? 0
    return message
  },
}

function createBaseRagQueryResponse(): RagQueryResponse {
  return { outcome: 0, summary: '', sources: [], chunks: [] }
}

export const RagQueryResponse: MessageFns<RagQueryResponse> = {
  encode(message: RagQueryResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.outcome !== 0) {
      writer.uint32(8).int32(message.outcome)
    }
    if (message.summary !== '') {
      writer.uint32(18).string(message.summary)
    }
    for (const v of message.sources) {
      RagSource.encode(v!, writer.uint32(26).fork()).join()
    }
    for (const v of message.chunks) {
      RagChunk.encode(v!, writer.uint32(34).fork()).join()
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RagQueryResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseRagQueryResponse()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break
          }

          message.outcome = reader.int32() as any
          continue
        }
        case 2: {
          if (tag !== 18) {
            break
          }

          message.summary = reader.string()
          continue
        }
        case 3: {
          if (tag !== 26) {
            break
          }

          message.sources.push(RagSource.decode(reader, reader.uint32()))
          continue
        }
        case 4: {
          if (tag !== 34) {
            break
          }

          message.chunks.push(RagChunk.decode(reader, reader.uint32()))
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): RagQueryResponse {
    return {
      outcome: isSet(object.outcome) ? ragOutcomeFromJSON(object.outcome) : 0,
      summary: isSet(object.summary) ? globalThis.String(object.summary) : '',
      sources: globalThis.Array.isArray(object?.sources)
        ? object.sources.map((e: any) => RagSource.fromJSON(e))
        : [],
      chunks: globalThis.Array.isArray(object?.chunks)
        ? object.chunks.map((e: any) => RagChunk.fromJSON(e))
        : [],
    }
  },

  toJSON(message: RagQueryResponse): unknown {
    const obj: any = {}
    if (message.outcome !== 0) {
      obj.outcome = ragOutcomeToJSON(message.outcome)
    }
    if (message.summary !== '') {
      obj.summary = message.summary
    }
    if (message.sources?.length) {
      obj.sources = message.sources.map((e) => RagSource.toJSON(e))
    }
    if (message.chunks?.length) {
      obj.chunks = message.chunks.map((e) => RagChunk.toJSON(e))
    }
    return obj
  },

  create<I extends Exact<DeepPartial<RagQueryResponse>, I>>(base?: I): RagQueryResponse {
    return RagQueryResponse.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<RagQueryResponse>, I>>(object: I): RagQueryResponse {
    const message = createBaseRagQueryResponse()
    message.outcome = object.outcome ?? 0
    message.summary = object.summary ?? ''
    message.sources = object.sources?.map((e) => RagSource.fromPartial(e)) || []
    message.chunks = object.chunks?.map((e) => RagChunk.fromPartial(e)) || []
    return message
  },
}

function createBaseRagSource(): RagSource {
  return { knowledgeItemId: '', title: '' }
}

export const RagSource: MessageFns<RagSource> = {
  encode(message: RagSource, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.knowledgeItemId !== '') {
      writer.uint32(10).string(message.knowledgeItemId)
    }
    if (message.title !== '') {
      writer.uint32(18).string(message.title)
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RagSource {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseRagSource()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.knowledgeItemId = reader.string()
          continue
        }
        case 2: {
          if (tag !== 18) {
            break
          }

          message.title = reader.string()
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): RagSource {
    return {
      knowledgeItemId: isSet(object.knowledgeItemId)
        ? globalThis.String(object.knowledgeItemId)
        : isSet(object.knowledge_item_id)
          ? globalThis.String(object.knowledge_item_id)
          : '',
      title: isSet(object.title) ? globalThis.String(object.title) : '',
    }
  },

  toJSON(message: RagSource): unknown {
    const obj: any = {}
    if (message.knowledgeItemId !== '') {
      obj.knowledgeItemId = message.knowledgeItemId
    }
    if (message.title !== '') {
      obj.title = message.title
    }
    return obj
  },

  create<I extends Exact<DeepPartial<RagSource>, I>>(base?: I): RagSource {
    return RagSource.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<RagSource>, I>>(object: I): RagSource {
    const message = createBaseRagSource()
    message.knowledgeItemId = object.knowledgeItemId ?? ''
    message.title = object.title ?? ''
    return message
  },
}

function createBaseRagChunk(): RagChunk {
  return { knowledgeItemId: '', titleSnapshot: '', content: '', score: 0 }
}

export const RagChunk: MessageFns<RagChunk> = {
  encode(message: RagChunk, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.knowledgeItemId !== '') {
      writer.uint32(10).string(message.knowledgeItemId)
    }
    if (message.titleSnapshot !== '') {
      writer.uint32(18).string(message.titleSnapshot)
    }
    if (message.content !== '') {
      writer.uint32(26).string(message.content)
    }
    if (message.score !== 0) {
      writer.uint32(33).double(message.score)
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RagChunk {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseRagChunk()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.knowledgeItemId = reader.string()
          continue
        }
        case 2: {
          if (tag !== 18) {
            break
          }

          message.titleSnapshot = reader.string()
          continue
        }
        case 3: {
          if (tag !== 26) {
            break
          }

          message.content = reader.string()
          continue
        }
        case 4: {
          if (tag !== 33) {
            break
          }

          message.score = reader.double()
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): RagChunk {
    return {
      knowledgeItemId: isSet(object.knowledgeItemId)
        ? globalThis.String(object.knowledgeItemId)
        : isSet(object.knowledge_item_id)
          ? globalThis.String(object.knowledge_item_id)
          : '',
      titleSnapshot: isSet(object.titleSnapshot)
        ? globalThis.String(object.titleSnapshot)
        : isSet(object.title_snapshot)
          ? globalThis.String(object.title_snapshot)
          : '',
      content: isSet(object.content) ? globalThis.String(object.content) : '',
      score: isSet(object.score) ? globalThis.Number(object.score) : 0,
    }
  },

  toJSON(message: RagChunk): unknown {
    const obj: any = {}
    if (message.knowledgeItemId !== '') {
      obj.knowledgeItemId = message.knowledgeItemId
    }
    if (message.titleSnapshot !== '') {
      obj.titleSnapshot = message.titleSnapshot
    }
    if (message.content !== '') {
      obj.content = message.content
    }
    if (message.score !== 0) {
      obj.score = message.score
    }
    return obj
  },

  create<I extends Exact<DeepPartial<RagChunk>, I>>(base?: I): RagChunk {
    return RagChunk.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<RagChunk>, I>>(object: I): RagChunk {
    const message = createBaseRagChunk()
    message.knowledgeItemId = object.knowledgeItemId ?? ''
    message.titleSnapshot = object.titleSnapshot ?? ''
    message.content = object.content ?? ''
    message.score = object.score ?? 0
    return message
  },
}

/**
 * Internal service-to-service contract, NOT public API. Called by core-api's
 * AI-Query Saga to run one paid RAG query against search-service, which owns
 * the embeddings + Elasticsearch index and is the only place the retrieval
 * pipeline lives. Secured by shared-secret metadata (x-internal-secret), same
 * convention as membership.proto / org-provisioning.proto.
 *
 * This RPC deliberately does NOT verify org membership: core-api has already
 * authenticated the caller (JWT + OrgGuard + KNOWLEDGE_READ/CREDIT_SPEND) before
 * the saga starts, and the shared secret is the trust boundary here. Do not read
 * the absence of a membership check as the IDOR regression fixed in 2026-07-19 —
 * that one was about a PUBLIC HTTP endpoint trusting a client-supplied X-Org-Id.
 */
export type RagQueryService = typeof RagQueryService
export const RagQueryService = {
  query: {
    path: '/cortex.search.RagQuery/Query' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: RagQueryRequest): Buffer =>
      Buffer.from(RagQueryRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): RagQueryRequest => RagQueryRequest.decode(value),
    responseSerialize: (value: RagQueryResponse): Buffer =>
      Buffer.from(RagQueryResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): RagQueryResponse => RagQueryResponse.decode(value),
  },
} as const

export interface RagQueryServer extends UntypedServiceImplementation {
  query: handleUnaryCall<RagQueryRequest, RagQueryResponse>
}

export interface RagQueryClient extends Client {
  query(
    request: RagQueryRequest,
    callback: (error: ServiceError | null, response: RagQueryResponse) => void,
  ): ClientUnaryCall
  query(
    request: RagQueryRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: RagQueryResponse) => void,
  ): ClientUnaryCall
  query(
    request: RagQueryRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: RagQueryResponse) => void,
  ): ClientUnaryCall
}

export const RagQueryClient = makeGenericClientConstructor(
  RagQueryService,
  'cortex.search.RagQuery',
) as unknown as {
  new (
    address: string,
    credentials: ChannelCredentials,
    options?: Partial<ClientOptions>,
  ): RagQueryClient
  service: typeof RagQueryService
  serviceName: string
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>

type KeysOfUnion<T> = T extends T ? keyof T : never
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never }

function isSet(value: any): boolean {
  return value !== null && value !== undefined
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter
  decode(input: BinaryReader | Uint8Array, length?: number): T
  fromJSON(object: any): T
  toJSON(message: T): unknown
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T
}
