// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.0
//   protoc               v7.35.1
// source: system-rbac.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from '@bufbuild/protobuf/wire'
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from '@grpc/grpc-js'

export const protobufPackage = 'cortex.auth'

export interface ResolveSystemPermissionsRequest {
  userId: string
}

export interface ResolveSystemPermissionsResponse {
  /**
   * Empty for an unknown, deleted, or inactive user, and for a real user who
   * simply holds no system role — all four are "no platform privileges", which
   * is the same authorization answer, so they are deliberately NOT
   * distinguished on the wire.
   */
  permissions: string[]
}

function createBaseResolveSystemPermissionsRequest(): ResolveSystemPermissionsRequest {
  return { userId: '' }
}

export const ResolveSystemPermissionsRequest: MessageFns<ResolveSystemPermissionsRequest> = {
  encode(
    message: ResolveSystemPermissionsRequest,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.userId !== '') {
      writer.uint32(10).string(message.userId)
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ResolveSystemPermissionsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseResolveSystemPermissionsRequest()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.userId = reader.string()
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): ResolveSystemPermissionsRequest {
    return {
      userId: isSet(object.userId)
        ? globalThis.String(object.userId)
        : isSet(object.user_id)
          ? globalThis.String(object.user_id)
          : '',
    }
  },

  toJSON(message: ResolveSystemPermissionsRequest): unknown {
    const obj: any = {}
    if (message.userId !== '') {
      obj.userId = message.userId
    }
    return obj
  },

  create<I extends Exact<DeepPartial<ResolveSystemPermissionsRequest>, I>>(
    base?: I,
  ): ResolveSystemPermissionsRequest {
    return ResolveSystemPermissionsRequest.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<ResolveSystemPermissionsRequest>, I>>(
    object: I,
  ): ResolveSystemPermissionsRequest {
    const message = createBaseResolveSystemPermissionsRequest()
    message.userId = object.userId ?? ''
    return message
  },
}

function createBaseResolveSystemPermissionsResponse(): ResolveSystemPermissionsResponse {
  return { permissions: [] }
}

export const ResolveSystemPermissionsResponse: MessageFns<ResolveSystemPermissionsResponse> = {
  encode(
    message: ResolveSystemPermissionsResponse,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    for (const v of message.permissions) {
      writer.uint32(10).string(v!)
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ResolveSystemPermissionsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseResolveSystemPermissionsResponse()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.permissions.push(reader.string())
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): ResolveSystemPermissionsResponse {
    return {
      permissions: globalThis.Array.isArray(object?.permissions)
        ? object.permissions.map((e: any) => globalThis.String(e))
        : [],
    }
  },

  toJSON(message: ResolveSystemPermissionsResponse): unknown {
    const obj: any = {}
    if (message.permissions?.length) {
      obj.permissions = message.permissions
    }
    return obj
  },

  create<I extends Exact<DeepPartial<ResolveSystemPermissionsResponse>, I>>(
    base?: I,
  ): ResolveSystemPermissionsResponse {
    return ResolveSystemPermissionsResponse.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<ResolveSystemPermissionsResponse>, I>>(
    object: I,
  ): ResolveSystemPermissionsResponse {
    const message = createBaseResolveSystemPermissionsResponse()
    message.permissions = object.permissions?.map((e) => e) || []
    return message
  },
}

/**
 * Internal service-to-service contract, NOT public API. Called by core-api's
 * SystemPermissionGuard to resolve a caller's SYSTEM-level permissions against
 * auth_db, which is the only place System RBAC lives. Secured by shared-secret
 * metadata (x-internal-secret), same convention as membership.proto /
 * org-provisioning.proto.
 *
 * WHY THIS EXISTS (2026-08-25): core-api used to read the `permissions` claim
 * straight out of the JWT. That made platform-admin authorization a snapshot
 * taken at login: revoking SUPER_ADMIN left the old token fully privileged for
 * the remainder of its 15-minute life, and there was no way to shorten that
 * without shortening every token. Org RBAC never had this problem because
 * OrgGuard resolves from the DB per request — this contract closes the same gap
 * for the system tier. `.ai/memory/gotchas.jsonl` already recorded the root
 * cause: "any implicit-all / role-shortcut design that lives only in a
 * JWT-claim-checking guard MUST be expanded at token-mint time, not assumed".
 *
 * The response is the FULLY RESOLVED permission list, not the role names:
 * SUPER_ADMIN's implicit-all expansion happens here, on the side that owns the
 * rule, so core-api never re-derives it and the two cannot drift.
 */
export type SystemRbacService = typeof SystemRbacService
export const SystemRbacService = {
  resolveSystemPermissions: {
    path: '/cortex.auth.SystemRbac/ResolveSystemPermissions' as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: ResolveSystemPermissionsRequest): Buffer =>
      Buffer.from(ResolveSystemPermissionsRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ResolveSystemPermissionsRequest =>
      ResolveSystemPermissionsRequest.decode(value),
    responseSerialize: (value: ResolveSystemPermissionsResponse): Buffer =>
      Buffer.from(ResolveSystemPermissionsResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ResolveSystemPermissionsResponse =>
      ResolveSystemPermissionsResponse.decode(value),
  },
} as const

export interface SystemRbacServer extends UntypedServiceImplementation {
  resolveSystemPermissions: handleUnaryCall<
    ResolveSystemPermissionsRequest,
    ResolveSystemPermissionsResponse
  >
}

export interface SystemRbacClient extends Client {
  resolveSystemPermissions(
    request: ResolveSystemPermissionsRequest,
    callback: (error: ServiceError | null, response: ResolveSystemPermissionsResponse) => void,
  ): ClientUnaryCall
  resolveSystemPermissions(
    request: ResolveSystemPermissionsRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ResolveSystemPermissionsResponse) => void,
  ): ClientUnaryCall
  resolveSystemPermissions(
    request: ResolveSystemPermissionsRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ResolveSystemPermissionsResponse) => void,
  ): ClientUnaryCall
}

export const SystemRbacClient = makeGenericClientConstructor(
  SystemRbacService,
  'cortex.auth.SystemRbac',
) as unknown as {
  new (
    address: string,
    credentials: ChannelCredentials,
    options?: Partial<ClientOptions>,
  ): SystemRbacClient
  service: typeof SystemRbacService
  serviceName: string
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>

type KeysOfUnion<T> = T extends T ? keyof T : never
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never }

function isSet(value: any): boolean {
  return value !== null && value !== undefined
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter
  decode(input: BinaryReader | Uint8Array, length?: number): T
  fromJSON(object: any): T
  toJSON(message: T): unknown
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T
}
