apiVersion: 1

contactPoints:
  - orgId: 1
    name: cortex-default
    receivers:
      - uid: cortex-default-webhook
        type: webhook
        settings:
          url: http://host.docker.internal:9999/grafana-alerts
          httpMethod: POST
        disableResolveMessage: false
